version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_vol:/var/lib/postgresql
      - db_vol_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: "service_healthy"

volumes:
  db_vol:
  db_vol_data:
