# Generated by Django 5.0.4 on 2024-04-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
