# Generated by Django 5.0.4 on 2024-04-23 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20240423_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-updated_at']},
        ),
    ]
