# Generated by Django 5.0.4 on 2024-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
