# Generated by Django 5.0.4 on 2024-04-23 01:11

import logging

from django.db import migrations


def create_default_currencies(apps, schema_editor):
    Currency = apps.get_model("currency", "Currency")

    # Values from py-money python package
    default_currencies_dict = {
        "ARS": "Peso Argentino",
        "AUD": "Dólar Australiano",
        "BRL": "Real Brasileiro",
        "CAD": "Dólar Canadense",
        "EUR": "Euro",
        "GBP": "Libra Esterlina",
        "JPY": "Iene",
        "MXN": "Peso Mexicano",
        "RUB": "Rublo Russo",
        "USD": "Dólar Americano",
    }

    for representation, name in default_currencies_dict.items():
        try:
            Currency.objects.get_or_create(name=name, representation=representation)
        except Exception as err:
            logging.warning(
                "Could not create default currency: {} ({})".format(
                    name, representation
                )
            )
            logging.warning(str(err))


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_currencies)]
