# Generated by Django 5.0.4 on 2024-04-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20240417_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['representation', 'name']},
        ),
    ]
