# Generated by Django 5.0.4 on 2024-04-30 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('name', 'user')},
        ),
    ]
