# Generated by Django 5.0.4 on 2024-04-30 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('name', 'user')},
        ),
    ]
